files:
  - source: /**/*.md
    ignore:
      - /de/
      - /es/
      - /fr/
      - /ja/
      - /ko/
      - /pt-BR/
      - /ru/
      - /tr/
      - /zh-CN/
      - /CONTRIBUTING.md
    translation: /%two_letters_code%/%original_path%/%original_file_name%
